services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  springboot:
    image: openjdk:21
    container_name: springboot-container
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    volumes:
      - ./build\libs\retail-restful-service-1.0.0.jar:/app.jar
    command: ["java", "-jar", "/app.jar"]
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongodb-container:27017
